import React, { createContext, useContext, useState, useEffect } from 'react';

const ThemeContext = createContext();

export const useTheme = () => useContext(ThemeContext);

export const ThemeProvider = ({ children }) => {
  const [theme, setTheme] = useState('light');
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') || 'light';
    const savedLanguage = localStorage.getItem('language') || 'en';
    setTheme(savedTheme);
    setLanguage(savedLanguage);
    document.documentElement.setAttribute('data-theme', savedTheme);
    document.documentElement.setAttribute('lang', savedLanguage);
    document.documentElement.setAttribute('dir', savedLanguage === 'ar' ? 'rtl' : 'ltr');
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(newTheme);
    localStorage.setItem('theme', newTheme);
    document.documentElement.setAttribute('data-theme', newTheme);
  };

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'ar' : 'en';
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
    document.documentElement.setAttribute('lang', newLanguage);
    document.documentElement.setAttribute('dir', newLanguage === 'ar' ? 'rtl' : 'ltr');
  };

  const translations = {
    en: {
      home: 'Home',
      games: 'Games',
      leaderboard: 'Leaderboard',
      profile: 'Profile',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      startGame: 'Start Game',
      score: 'Score',
      time: 'Time',
      matches: 'Matches',
      materialMaster: 'Material Master',
      materialMasterInstr1: '✅ Match materials with their best use case',
      materialMasterInstr2: '⏱️ You have 90 seconds',
      materialMasterInstr3: '💯 Each match = 100 points',
      materialMasterInstr4: '🏆 Make it to the leaderboard!',
      ecoMemoryInstr1: '✅ Flip two cards to match the recycling item with the correct bin',
      ecoMemoryInstr2: '🧠 Look for patterns and remember the card positions',
      ecoMemoryInstr3: '💯 Each match gives 120 points',
      ecoMemoryInstr4: '🎯 Match all the pairs to win',
      wasteSortingInstr1: '✅ Drag each item to the bin it belongs in',
      wasteSortingInstr2: '💯 Correct sorts give 100 points',
      wasteSortingInstr3: '⚠️ 3 wrong drops ends the game',
      wasteSortingInstr4: '⏱️ Finish as many as possible in 60 seconds',
      wasteSortingDescription: 'Sort waste into the right recycling bin before time runs out.',
      ecoMemoryDescription: 'Memorize the cards, then match items to the correct bin.',
      items: 'Items',
      bins: 'Bins',
      binPaper: 'Paper',
      binPlastic: 'Plastic',
      binMetal: 'Metal',
      binGlass: 'Glass',
      binOrganic: 'Organic',
      binHazardous: 'Hazardous',
      binGeneral: 'General',
      remaining: 'Remaining',
      points: 'Points',
      preview: 'Preview',
      previewStartMessage: 'Memorize all cards. The game starts in 5 seconds!',
      matchCardsPrompt: 'Match the item with the correct bin.',
      matchSuccess: '✅ Match! Great job.',
      matchFail: '❌ Not a match. Try again.',
      memoryMatchComplete: 'Memory Match Complete!',
      ecoMemoryFinishGreat: 'Excellent memory! You matched every pair quickly.',
      ecoMemoryFinishGood: 'Well done! Keep improving your recycling recall.',
      wasteSortingFinishAll: 'Great work! You sorted all the items.',
      wasteSortingFinishPartial: 'Nice attempt! Practice makes sorting easier.',
      selectGame: 'Select game',
      topPlayersFor: 'Top players for',
      quizInstr1: '✅ Pick the correct recycling answer',
      quizInstr2: '⏱️ 60 seconds total time',
      quizInstr3: '💯 150 points per correct answer',
      quizInstr4: '🏆 Save your score and climb the leaderboard',
      question: 'Question',
      trashTossInstr1: '✅ Pick the correct bin for the item shown',
      trashTossInstr2: '⏱️ You have 60 seconds',
      trashTossInstr3: '💯 Each correct toss = 100 points',
      trashTossInstr4: '🏆 Save your score when you finish',
      pollutionCleanupInstr1: '✅ Click trash cards on the beach to clean them up',
      pollutionCleanupInstr2: '💯 Each item gives points, and boosts increase your cleaning power',
      pollutionCleanupInstr3: '⏱️ You have 30 seconds to remove as much pollution as possible',
      pollutionCleanupInstr4: '🎯 Finish the beach or get a high score before time expires',
      carbonFootprintInstr1: '✅ Pick the most sustainable choice for each scenario',
      carbonFootprintInstr2: '💯 Better choices earn more points',
      carbonFootprintInstr3: '🎯 Finish 5 scenarios to complete the adventure',
      matchMaterials: 'Match recycled materials to their industries!',
      material: 'Material',
      matchMaterials: 'Match recycled materials to their industries!',
      timeLeft: 'Time Left',
      gameOver: 'Game Over!',
      youWin: 'You Win!',
      tryAgain: 'Try Again',
      backToGames: 'Back to Games',
      perfectMatch: '🎉 Perfect! You matched everything!',
      goodEffort: 'Good effort! You matched',
      pairs: 'pairs',
      saveScore: '📊 Save Score & View Leaderboard',
      playAgain: 'Play Again',
      itemLabel: 'ITEM',
      binLabel: 'BIN',
      loginToSave: 'Log in to save your score!',
      saving: 'Saving...',
      welcome: 'Welcome to RecycleX',
      subtitle: 'The sustainable marketplace for recycled materials',
      circularMarketplace: 'Circular marketplace',
      getStarted: 'Get Started',
      learnMore: 'Learn More',
      username: 'Username',
      password: 'Password',
      email: 'Email',
      confirmPassword: 'Confirm Password',
      fullName: 'Full Name',
      role: 'Role',
      buyer: 'Buyer',
      seller: 'Seller',
      admin: 'Admin',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      createAccount: 'Create Account',
      alreadyHaveAccount: 'Already have an account?',
      dontHaveAccount: "Don't have an account?",
      forgotPassword: 'Forgot Password?',
      marketplace: 'Marketplace',
      search: 'Search',
      filter: 'Filter',
      sortBy: 'Sort By',
      price: 'Price',
      location: 'Location',
      category: 'Category',
      description: 'Description',
      contact: 'Contact',
      submit: 'Submit',
      cancel: 'Cancel',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      dashboard: 'Dashboard',
      orders: 'Orders',
      requests: 'Requests',
      listings: 'Listings',
      users: 'Users',
      testimonials: 'Testimonials',
      approvals: 'Approvals',
      settings: 'Settings',
      welcomeBack: 'Welcome back',
      manageListings: 'Manage your listings and connect with buyers.',
      discoverMaterials: 'Discover surplus materials and track your requests.',
      approvedListings: 'Approved listings',
      activeListings: 'Active listings',
      incomingRequests: 'Incoming requests',
      pendingRequests: 'Pending requests',
      activeOrders: 'Active orders',
      itemsTraded: 'Items traded',
      myListings: 'My listings',
      manageTrackListings: 'Manage and track your material listings.',
      active: 'active',
      goToListings: 'Go to listings',
      marketplace: 'Marketplace',
      browseSurplus: 'Browse surplus materials from sellers.',
      explore: 'Explore',
      browseMaterials: 'Browse materials',
      myRequests: 'My requests',
      trackRequests: 'Track requests you sent to sellers.',
      pending: 'pending',
      viewRequests: 'View requests',
      incomingRequestsDesc: 'Respond to buyers interested in your listings.',
      orders: 'Orders',
      trackOrders: 'Track orders and transactions.',
      total: 'total',
      viewOrders: 'View orders',
      payments: 'Payments',
      mockPayments: 'Mock payments are recorded when you pay from the Orders page.',
      recorded: 'recorded',
      ordersPay: 'Orders & pay',
      accountProfile: 'Account and profile preferences.',
      profile: 'Profile',
      goToProfile: 'Go to profile',
      materialMaster: 'Material Master',
      trashToss: 'Trash Toss',
      recyclingQuiz: 'Recycling Quiz',
      ecoMemory: 'Eco Memory',
      wasteSorting: 'Waste Sorting',
      carbonAdventure: 'Carbon Adventure',
      pollutionCleanup: 'Pollution Cleanup',
      today: 'Today',
      thisWeek: 'This Week',
      allTime: 'All Time',
      rank: 'Rank',
      player: 'Player',
      score: 'Score',
      date: 'Date',
      st: 'st',
      nd: 'nd',
      rd: 'rd',
      th: 'th',
      recently: 'Recently',
      wantToSeeName: 'Want to see your name on the leaderboard?',
      playNow: 'Play Now',
      browseMaterials: 'Browse Materials',
      browseMarketplace: 'Browse marketplace',
      browseMarketplaceMessage: 'Browse the marketplace and send a request on a listing you like.',
      discoverSustainable: 'Discover sustainable surplus materials from businesses and individuals.',
      filtersSearch: 'Filters & Search',
      searchMaterials: 'Search materials...',
      allCategories: 'All Categories',
      allPrices: 'All Prices',
      latest: 'Latest',
      priceLowToHigh: 'Price: Low to High',
      priceHighToLow: 'Price: High to Low',
      nameAToZ: 'Name: A to Z',
      clearAllFilters: 'Clear all filters',
      loadingMaterials: 'Loading materials…',
      showingMaterials: 'Showing',
      materials: 'materials',
      qty: 'Qty',
      viewDetails: 'View details',
      noMaterialsFound: 'No materials found',
      tryAdjustingFilters: 'Try adjusting your filters or search query.',
      clearFilters: 'Clear filters',
      noDescription: 'No description provided.',
      turnSurplusIntoSuccess: 'Turn Surplus into Success',
      joinCircularEconomy: 'Join the circular economy revolution. Exchange surplus materials, reduce waste, and create value from what others no longer need.',
      browseMaterials: 'Browse Materials',
      getStartedToday: 'Get Started Today',
      getStartedSubtitle: 'Whether you\'re looking to buy sustainable materials or sell your surplus, we\'ve got you covered.',
      imABuyer: 'I\'m a Buyer',
      buyerDesc: 'Find high-quality surplus materials at competitive prices. Save money while supporting sustainability.',
      imASeller: 'I\'m a Seller',
      sellerDesc: 'List your surplus materials and connect with buyers who need them. Turn waste into revenue.',
      listYourMaterials: 'List Your Materials',
      loading: 'Loading...',
      findWhatYouNeed: 'Find What You Need',
      searchMaterials: 'Search materials...',
      allCategories: 'All Categories',
      searchMaterialsBtn: 'Search Materials',
      browseByCategory: 'Browse by Category',
      items: 'items',
      featuredMaterials: 'Featured Materials',
      latestAdditions: 'Latest additions to our marketplace',
      viewAll: 'View All',
      noFeaturedMaterials: 'No featured materials yet.',
      viewDetails: 'View Details',
      howItWorks: 'How It Works',
      howItWorksSubtitle: 'Getting started with RecycleX is simple. Follow these three easy steps to start exchanging materials.',
      addMaterials: 'Add Materials',
      addMaterialsDesc: 'List your surplus materials with photos, descriptions, and pricing. It\'s quick and easy!',
      sendRequests: 'Send Requests',
      sendRequestsDesc: 'Browse materials and send requests to sellers. Communicate directly to discuss details.',
      completeOrders: 'Complete Orders',
      completeOrdersDesc: 'Finalize the transaction and arrange delivery. Build sustainable business relationships!',
      startYourJourney: 'Start Your Journey',
      whatOurUsersSay: 'What Our Users Say',
      usersSaySubtitle: 'Hear from businesses and individuals making a difference in the circular economy.',
      testimonialsNote: 'Approved testimonials appear here after admin review. Submit yours below.',
      shareYourExperience: 'Share your experience',
      testimonialReviewNote: 'Your testimonial will be reviewed by an admin before it appears publicly.',
      name: 'Name',
      roleOptional: 'Role (optional)',
      rolePlaceholder: 'Buyer / Factory Owner / Manager...',
      testimonial: 'Testimonial',
      ratingOptional: 'Rating (optional)',
      submit: 'Submit',
      submitting: 'Submitting...',
      testimonialSubmitted: 'Thanks! Your testimonial was submitted and is pending approval.',
      failedToSubmit: 'Failed to submit testimonial.',
      noRating: 'No rating',
      clear: 'Clear',
      submitTestimonial: 'Submit testimonial',
      readyToMakeDifference: 'Ready to Make a Difference?',
      ctaText: 'Join thousands of businesses and individuals reducing waste and creating value through the circular economy.',
      createFreeAccount: 'Create Free Account',
      explorePlatform: 'Explore Platform',
      loadingProfile: 'Loading profile…',
      unableToLoadProfile: 'Unable to load profile.',
      joined: 'Joined',
      // Profile form
      editProfile: 'Edit Profile',
      nameRequired: 'Name is required',
      nameTooLong: 'Name is too long',
      phoneInvalid: 'Phone looks invalid',
      locationTooLong: 'Too long',
      bioMaxChars: 'Max 2000 characters',
      saveProfile: 'Save Profile',
      saving: 'Saving...',
      profileSaved: 'Profile saved.',
      failedToSaveProfile: 'Failed to save profile.',
      reset: 'Reset',
      // Password
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      required: 'Required',
      atLeast6Chars: 'At least 6 characters',
      mustDiffer: 'Must differ from current',
      passwordsDontMatch: 'Passwords do not match',
      updatePassword: 'Update Password',
      passwordUpdated: 'Password updated.',
      failedToChangePassword: 'Failed to change password.',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      // Activity
      recentActivity: 'Recent Activity',
      materialsListed: 'Materials Listed',
      requestsSent: 'Requests Sent',
      ordersCompleted: 'Orders Completed',
      accountInformation: 'Account information',
      fullName: 'Full name',
      email: 'Email',
      emailCannotBeChanged: 'Email cannot be changed yet.',
      phone: 'Phone',
      phonePlaceholder: '+20 100 123 4567',
      location: 'Location',
      locationPlaceholder: 'City, Country',
      bio: 'Bio',
      sellerBioPlaceholder: 'Tell buyers about your business, specialties, and delivery areas.',
      buyerBioPlaceholder: 'A short intro about you or your projects.',
      saveChanges: 'Save changes',
      discard: 'Discard',
      // Activity labels
      myListings: 'My listings',
      incomingRequests: 'Incoming requests',
      myRequests: 'My requests',
      orders: 'Orders',
      messages: 'Messages',
      rating: 'Rating',
      // Password form
      currentPasswordRequired: 'Current password is required',
      newPasswordRequired: 'New password is required',
      security: 'Security',
      cancel: 'Cancel',
      changePassword: 'Change password',
      keepAccountSecure: 'Keep your account secure by using a strong, unique password.',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmNewPassword: 'Confirm new password',
      updatePassword: 'Update password',
      quickLinks: 'Quick links',
      manageListings: 'Manage listings',
      incomingRequests: 'Incoming requests',
      browseMarketplace: 'Browse marketplace',
      browseMarketplaceMessage: 'Browse the marketplace and send a request on a listing you like.',
      myRequests: 'My requests',
      myRequestsLead: 'Track messages and status for materials you asked sellers about.',
      loadingRequests: 'Loading requests…',
      failedLoadRequests: 'Failed to load your requests.',
      noRequestsYet: 'No requests yet',
      messageSeller: 'Message seller',
      viewMaterial: 'View material',
      adminDashboard: 'Admin dashboard',
      testimonialApprovals: 'Testimonial approvals',
      approveOrRejectTestimonials: 'Approve or reject submitted testimonials.',
      loadingPendingTestimonials: 'Loading pending testimonials…',
      failedLoadTestimonials: 'Failed to load testimonial approvals.',
      noPendingTestimonials: 'No pending testimonials',
      pendingTestimonialsHelp: 'You can approve or reject testimonials as they arrive.',
      approve: 'Approve',
      reject: 'Reject',
      actionFailed: 'Action failed. Please try again.',
      hidePassword: 'Hide password',
      showPassword: 'Show password',
      // Game keys
      trashToss: 'Trash Toss',
      recyclingQuiz: 'Recycling Quiz',
      recyclingQuizDescription: 'Answer recycling questions fast and earn points.',
      recyclingQuizComplete: 'Quiz Complete!',
      recyclingQuizExcellent: 'Excellent! Your recycling knowledge is strong.',
      recyclingQuizGood: 'Nice work! Keep learning more tips.',
      recyclingQuizOkay: 'Good start! Practice helps you improve.',
      ecoMemory: 'Eco Memory',
      wasteSorting: 'Waste Sorting',
      carbonAdventure: 'Carbon Adventure',
      carbonFootprintDescription: 'Pick the most sustainable choice for each scenario.',
      carbonFootprintComplete: 'Carbon Adventure Complete!',
      carbonFootprintExcellent: 'Eco-champion! Your choices were very green.',
      carbonFootprintGood: 'Solid effort! There is room to improve.',
      carbonFootprintOkay: 'Keep going! Try making greener choices next time.',
      youChose: 'You chose',
      footprintScore: 'Footprint Score',
      scenario: 'Scenario',
      pollutionCleanup: 'Pollution Cleanup',
      pollutionCleanupHeading: '🏖️ Beach Cleanup',
      pollutionCleanupDescription: 'Click trash items on the beach to clean them before time runs out.',
      beachCleanupComplete: 'Beach Cleanup Complete!',
      pollutionCleanupSuccess: 'Great work cleaning the beach!',
      pollutionCleanupFailed: 'Time ran out! Better luck next time.',
      boost: 'Boost',
      trashLeft: 'Trash left',
      clickFast: 'click fast',
      allTrashCleaned: 'All visible trash cleaned. Wait for your final score.',
      // Game finish messages
      gameFailed: 'Game Over - Failed!',
      scoreBelow100: 'Your score is below 100. Try again!',
      tooManyWrong: 'Too many wrong answers! Game over.',
      // Recycle Bin Game
      recycleBinDescription: 'Correctly identify the bin for each piece of trash.',
      trashTossDescription: 'Toss trash items into the correct recycling bin.',
      trashTossComplete: 'Trash Toss Complete!',
      trashTossSuccess: 'You sorted the trash correctly!',
      trashTossFailed: 'Time ran out or too many mistakes!',
      // Marketplace keys
      loadingMaterials: 'Loading materials…',
      discoverSustainable: 'Discover sustainable surplus materials from businesses and individuals.',
      filtersSearch: 'Filters & Search',
      searchMaterials: 'Search materials...',
      allCategories: 'All Categories',
      allPrices: 'All Prices',
      priceLowToHigh: 'Price: Low to High',
      priceHighToLow: 'Price: High to Low',
      nameAToZ: 'Name: A to Z',
      clearAllFilters: 'Clear all filters',
      showingMaterials: 'Showing',
      materials: 'materials',
      noDescription: 'No description provided.',
      qty: 'Qty',
      viewDetails: 'View details',
      noMaterialsFound: 'No materials found',
      tryAdjustingFilters: 'Try adjusting your filters or search query.',
      clearFilters: 'Clear filters',
      failedLoadMarketplace: 'Failed to load marketplace items. Please try again later.',
      // Orders keys
      ordersDescriptionSeller: 'Orders that include your materials. After the buyer pays (mock), you can mark the order complete when fulfilled.',
      ordersDescriptionBuyer: 'Pay with the mock checkout to confirm an order, then you or the seller can mark it complete.',
      loadingOrders: 'Loading orders…',
      myRequests: 'My requests',
      myRequestsLead: 'Track messages and status for materials you asked sellers about.',
      loadingRequests: 'Loading requests…',
      failedLoadRequests: 'Failed to load your requests.',
      noRequestsYet: 'No requests yet',
      browseMarketplaceMessage: 'Browse the marketplace and send a request on a listing you like.',
      messageSeller: 'Message seller',
      viewMaterial: 'View material',
      failedLoadTestimonials: 'Failed to load pending testimonials.',
      loadingPendingTestimonials: 'Loading pending testimonials…',
      noPendingTestimonials: 'No pending testimonials',
      pendingTestimonialsHelp: 'New submissions will appear here for review.',
      testimonialApprovals: 'Testimonial Approvals',
      approveOrRejectTestimonials: 'Approve or reject testimonials before they appear on the home page.',
      approve: 'Approve',
      actionFailed: 'Action failed.',
      paymentFailed: 'Payment failed.',
      updateFailed: 'Update failed.',
      nameOnCardRequired: 'Name on card is required.',
      cardNumberRequired: 'Card number is required.',
      cardNumberInvalid: 'Card number looks invalid.',
      expiryRequired: 'Expiry is required (MM/YY).',
      expiryInvalid: 'Use MM/YY (e.g. 08/28).',
      cardExpired: 'Card is expired.',
      cvvRequired: 'CVV is required.',
      cvvInvalid: 'CVV must be 3–4 digits.',
      pay: 'Pay',
      markComplete: 'Mark Complete',
      cancelOrder: 'Cancel Order',
      status: 'Status',
      confirmed: 'Confirmed',
      completed: 'Completed',
      cancelled: 'Cancelled',
      quantity: 'Quantity',
      seller: 'Seller',
      buyer: 'Buyer',
      date: 'Date',
      actions: 'Actions',
      noOrders: 'No orders yet.',
      noOrdersMessage: 'When you buy materials, your orders will appear here.',
      // SellerIncomingRequests keys
      incomingRequests: 'Incoming requests',
      respondToBuyers: 'Respond to buyers who are interested in your listings.',
      showAcceptedRejected: 'Show accepted / rejected',
      loadingRequests: 'Loading requests…',
      failedLoadRequests: 'Failed to load incoming requests.',
      failedUpdateStatus: 'Failed to update status.',
      accept: 'Accept',
      reject: 'Reject',
      accepted: 'Accepted',
      rejected: 'Rejected',
      message: 'Message',
      viewListing: 'View Listing',
      noRequests: 'No requests yet.',
      noRequestsMessage: 'When buyers are interested in your listings, requests will appear here.',
      // SellerListings keys
      manageListingsDesc: 'Manage and track your material listings.',
      addNewListing: 'Add New Listing',
      title: 'Title',
      description: 'Description',
      quantity: 'Quantity',
      price: 'Price',
      category: 'Category',
      selectCategory: 'Select category...',
      image: 'Image',
      listingAdded: 'Listing added successfully.',
      failedAddListing: 'Failed to add listing.',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Are you sure you want to delete this listing?',
      deleteListing: 'Delete Listing',
      failedDelete: 'Failed to delete listing.',
      noListings: 'No listings yet.',
      noListingsMessage: 'Add your first listing to start selling surplus materials.',
      failedLoadListings: 'Failed to load your listings.',
      loadingListings: 'Loading your listings…',
      listingPendingHelp: 'New listings are created as pending until admin approval.',
      existingListings: 'Existing listings',
      emptyListingsMessage: 'Use the form to add your first material.',
      howToPlay: 'How to Play',
      createNewListing: 'Create new listing',
      egSurplusCotton: 'e.g. Surplus cotton fabric',
      describeCondition: 'Describe condition, packaging, notes...',
      optional: 'Optional',
      optionalUrl: 'Optional (URL or path)',
      orProvideUrl: 'Or provide a URL/path below (optional).',
      // RegisterForm keys
      joinCircularEconomy: 'Join the circular economy—list or find surplus materials in minutes.',
      fillDetails: 'Fill in your details to create a new account.',
      findSustainableMaterials: 'Find sustainable materials',
      listYourSurplus: 'List your surplus',
      // Add more as needed
    },
    ar: {
      home: 'الرئيسية',
      games: 'الألعاب',
      leaderboard: 'لوحة الصدارة',
      profile: 'الملف الشخصي',
      login: 'تسجيل الدخول',
      register: 'التسجيل',
      logout: 'تسجيل الخروج',
      startGame: 'ابدأ اللعبة',
      score: 'النقاط',
      time: 'الوقت',
      matches: 'المطابقات',
      materialMaster: 'سيد المواد',
      materialMasterInstr1: '✅ طابق المواد مع أفضل استخدام لها',
      materialMasterInstr2: '⏱️ لديك 90 ثانية',
      materialMasterInstr3: '💯 كل تطابق = 100 نقطة',
      materialMasterInstr4: '🏆 اصعد إلى لوحة الصدارة!',
      ecoMemoryInstr1: '✅ اقلب ورقتين لمطابقة عنصر إعادة التدوير بالصندوق الصحيح',
      ecoMemoryInstr2: '🧠 ابحث عن الأنماط وتذكر مواضع البطاقات',
      ecoMemoryInstr3: '💯 كل تطابق يمنح 120 نقطة',
      ecoMemoryInstr4: '🎯 طابق كل الأزواج للفوز',
      wasteSortingInstr1: '✅ اسحب كل عنصر إلى الصندوق الذي ينتمي إليه',
      wasteSortingInstr2: '💯 التصنيفات الصحيحة تمنح 100 نقطة',
      wasteSortingInstr3: '⚠️ ٣ إسقاطات خاطئة تنهي اللعبة',
      wasteSortingInstr4: '⏱️ اكمل أكبر عدد ممكن في 60 ثانية',
      wasteSortingDescription: 'فرز النفايات إلى الصندوق الصحيح قبل نفاد الوقت.',
      ecoMemoryDescription: 'احفظ البطاقات ثم طابق العناصر بالصندوق الصحيح.',
      items: 'عناصر',
      bins: 'صناديق',
      binPaper: 'ورق',
      binPlastic: 'بلاستيك',
      binMetal: 'معادن',
      binGlass: 'زجاج',
      binOrganic: 'عضوي',
      binHazardous: 'خطير',
      binGeneral: 'عام',
      remaining: 'المتبقي',
      points: 'النقاط',
      preview: 'عرض مسبق',
      previewStartMessage: 'تذكر البطاقات. تبدأ اللعبة بعد 5 ثوانٍ!',
      matchCardsPrompt: 'اطابق العنصر بالصندوق الصحيح.',
      matchSuccess: '✅ تطابق! أحسنت.',
      matchFail: '❌ ليست مطابقة. حاول مرة أخرى.',
      memoryMatchComplete: 'اكتمل مطابقة الذاكرة!',
      ecoMemoryFinishGreat: 'ذاكرة ممتازة! طابقت كل الأزواج بسرعة.',
      ecoMemoryFinishGood: 'عمل جيد! استمر في تحسين تذكرك لإعادة التدوير.',
      wasteSortingFinishAll: 'عمل رائع! فرزت جميع العناصر.',
      wasteSortingFinishPartial: 'محاولة جيدة! الممارسة تجعل الفرز أسهل.',
      selectGame: 'اختر اللعبة',
      topPlayersFor: 'أفضل اللاعبين في',
      quizInstr1: '✅ اختر الإجابة الصحيحة لإعادة التدوير',
      quizInstr2: '⏱️ 60 ثانية كوقت إجمالي',
      quizInstr3: '💯 150 نقطة عن كل إجابة صحيحة',
      quizInstr4: '🏆 احفظ نقاطك وتصدر لوحة الصدارة',
      question: 'السؤال',
      trashTossInstr1: '✅ اختر الصندوق الصحيح للعنصر المعروض',
      trashTossInstr2: '⏱️ لديك 60 ثانية',
      trashTossInstr3: '💯 كل رمية صحيحة = 100 نقطة',
      trashTossInstr4: '🏆 احفظ نقاطك عند الانتهاء',
      pollutionCleanupInstr1: '✅ انقر على بطاقات القمامة على الشاطئ لتنظيفها',
      pollutionCleanupInstr2: '💯 كل عنصر يمنحك نقاطاً، والتعزيزات تزيد من قوة التنظيف',
      pollutionCleanupInstr3: '⏱️ لديك 30 ثانية لإزالة أكبر قدر من التلوث',
      pollutionCleanupInstr4: '🎯 أنهِ الشاطئ أو احصل على نتيجة عالية قبل انتهاء الوقت',
      carbonFootprintInstr1: '✅ اختر الخيار الأكثر استدامة لكل سيناريو',
      carbonFootprintInstr2: '💯 الخيارات الأفضل تكسب نقاطاً أكثر',
      carbonFootprintInstr3: '🎯 أكمل 5 سيناريوهات لإنهاء المغامرة',
      matchMaterials: 'طابق المواد المعاد تدويرها مع صناعاتها!',
      matchMaterials: 'طابق المواد المعاد تدويرها مع صناعاتها!',
      timeLeft: 'الوقت المتبقي',
      gameOver: 'انتهت اللعبة!',
      youWin: 'فزت!',
      tryAgain: 'حاول مرة أخرى',
      backToGames: 'العودة إلى الألعاب',
      perfectMatch: '🎉 ممتاز! طابقت كل شيء!',
      goodEffort: 'جهد جيد! طابقت',
      pairs: 'أزواج',
      saveScore: '📊 احفظ النقاط واعرض لوحة الصدارة',
      playAgain: 'العب مرة أخرى',
      itemLabel: 'عنصر',
      binLabel: 'صندوق',
      loginToSave: 'سجل الدخول لحفظ نقاطك!',
      saving: 'يحفظ...',
      welcome: 'مرحباً بك في RecycleX',
      subtitle: 'السوق المستدام للمواد المعاد تدويرها',
      circularMarketplace: 'السوق الدائري',
      getStarted: 'ابدأ',
      learnMore: 'اعرف المزيد',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      email: 'البريد الإلكتروني',
      confirmPassword: 'تأكيد كلمة المرور',
      fullName: 'الاسم الكامل',
      role: 'الدور',
      buyer: 'مشتري',
      seller: 'بائع',
      admin: 'مدير',
      signIn: 'تسجيل الدخول',
      signUp: 'التسجيل',
      createAccount: 'إنشاء حساب',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      dontHaveAccount: 'ليس لديك حساب؟',
      forgotPassword: 'نسيت كلمة المرور؟',
      marketplace: 'السوق',
      search: 'بحث',
      filter: 'تصفية',
      sortBy: 'ترتيب حسب',
      price: 'السعر',
      location: 'الموقع',
      category: 'الفئة',
      description: 'الوصف',
      contact: 'اتصال',
      submit: 'إرسال',
      cancel: 'إلغاء',
      loading: 'جارٍ التحميل...',
      error: 'خطأ',
      success: 'نجح',
      dashboard: 'لوحة التحكم',
      orders: 'الطلبات',
      requests: 'الطلبات',
      listings: 'القوائم',
      users: 'المستخدمون',
      testimonials: 'الشهادات',
      approvals: 'الموافقات',
      settings: 'الإعدادات',
      welcomeBack: 'مرحباً بعودتك',
      manageListings: 'إدارة قوائمك والتواصل مع المشترين.',
      discoverMaterials: 'اكتشف المواد الزائدة وتتبع طلباتك.',
      approvedListings: 'القوائم المعتمدة',
      activeListings: 'القوائم النشطة',
      incomingRequests: 'الطلبات الواردة',
      pendingRequests: 'الطلبات المعلقة',
      activeOrders: 'الطلبات النشطة',
      itemsTraded: 'العناصر المتبادلة',
      myListings: 'قوائمي',
      manageTrackListings: 'إدارة وتتبع قوائم موادك.',
      active: 'نشط',
      goToListings: 'الذهاب إلى القوائم',
      marketplace: 'السوق',
      browseSurplus: 'تصفح المواد الزائدة من البائعين.',
      explore: 'استكشف',
      browseMaterials: 'تصفح المواد',
      browseMarketplaceMessage: 'تصفح السوق وأرسل طلباً على القائمة التي تعجبك.',
      myRequests: 'طلباتي',
      myRequestsLead: 'تتبع الرسائل وحالة المواد التي طلبتها من البائعين.',
      loadingRequests: 'جارٍ تحميل الطلبات…',
      failedLoadRequests: 'فشل في تحميل طلباتك.',
      noRequestsYet: 'لا توجد طلبات بعد',
      messageSeller: 'مراسلة البائع',
      viewMaterial: 'عرض المادة',
      trackRequests: 'تتبع الطلبات التي أرسلتها إلى البائعين.',
      pending: 'معلق',
      viewRequests: 'عرض الطلبات',
      incomingRequestsDesc: 'الرد على المشترين المهتمين بقوائمك.',
      orders: 'الطلبات',
      trackOrders: 'تتبع الطلبات والمعاملات.',
      total: 'إجمالي',
      viewOrders: 'عرض الطلبات',
      payments: 'المدفوعات',
      mockPayments: 'يتم تسجيل المدفوعات التجريبية عند الدفع من صفحة الطلبات.',
      recorded: 'مسجل',
      ordersPay: 'الطلبات والدفع',
      accountProfile: 'تفضيلات الحساب والملف الشخصي.',
      profile: 'الملف الشخصي',
      goToProfile: 'الذهاب إلى الملف الشخصي',
      materialMaster: 'سيد المواد',
      material: 'مادة',
      trashToss: 'رمي القمامة',
      recyclingQuiz: 'اختبار إعادة التدوير',
      ecoMemory: 'الذاكرة البيئية',
      wasteSorting: 'فرز النفايات',
      carbonAdventure: 'مغامرة الكربون',
      pollutionCleanup: 'تنظيف التلوث',
      today: 'اليوم',
      thisWeek: 'هذا الأسبوع',
      allTime: 'كل الأوقات',
      rank: 'الترتيب',
      player: 'اللاعب',
      score: 'النقاط',
      date: 'التاريخ',
      st: 'st',
      nd: 'nd',
      rd: 'rd',
      th: 'th',
      recently: 'مؤخراً',
      wantToSeeName: 'تريد رؤية اسمك على لوحة الصدارة؟',
      playNow: 'العب الآن',
      browseMaterials: 'تصفح المواد',
      discoverSustainable: 'اكتشف مواد زائدة مستدامة من الشركات والأفراد.',
      filtersSearch: 'التصفية والبحث',
      searchMaterials: 'البحث في المواد...',
      allCategories: 'جميع الفئات',
      allPrices: 'جميع الأسعار',
      latest: 'الأحدث',
      priceLowToHigh: 'السعر: من الأقل للأعلى',
      priceHighToLow: 'السعر: من الأعلى للأقل',
      nameAToZ: 'الاسم: أ إلى ي',
      clearAllFilters: 'مسح جميع التصفيات',
      loadingMaterials: 'جارٍ تحميل المواد…',
      showingMaterials: 'عرض',
      materials: 'مواد',
      qty: 'الكمية',
      viewDetails: 'عرض التفاصيل',
      noMaterialsFound: 'لم يتم العثور على مواد',
      tryAdjustingFilters: 'جرب تعديل التصفيات أو استعلام البحث.',
      clearFilters: 'مسح التصفيات',
      noDescription: 'لم يتم توفير وصف.',
      turnSurplusIntoSuccess: 'حول الفائض إلى نجاح',
      joinCircularEconomy: 'انضم إلى ثورة الاقتصاد الدائري. تبادل المواد الزائدة، قلل النفايات، وأنشئ قيمة مما لا يحتاجه الآخرون.',
      browseMaterials: 'تصفح المواد',
      getStartedToday: 'ابدأ اليوم',
      getStartedSubtitle: 'سواء كنت تبحث عن شراء مواد مستدامة أو بيع فائضك، فنحن نوفر لك التغطية.',
      imABuyer: 'أنا مشتري',
      buyerDesc: 'اعثر على مواد زائدة عالية الجودة بأسعار تنافسية. وفر المال مع دعم الاستدامة.',
      imASeller: 'أنا بائع',
      sellerDesc: 'سجل موادك الزائدة وتواصل مع المشترين الذين يحتاجونها. حول النفايات إلى إيرادات.',
      listYourMaterials: 'سجل موادك',
      loading: 'جارٍ التحميل...',
      findWhatYouNeed: 'اعثر على ما تحتاجه',
      searchMaterials: 'البحث في المواد...',
      allCategories: 'جميع الفئات',
      searchMaterialsBtn: 'البحث في المواد',
      browseByCategory: 'التصفح حسب الفئة',
      items: 'عناصر',
      featuredMaterials: 'المواد المميزة',
      latestAdditions: 'أحدث الإضافات إلى السوق',
      viewAll: 'عرض الكل',
      noFeaturedMaterials: 'لا توجد مواد مميزة بعد.',
      viewDetails: 'عرض التفاصيل',
      howItWorks: 'كيف يعمل',
      howItWorksSubtitle: 'البدء مع RecycleX بسيط. اتبع هذه الخطوات الثلاث السهلة لبدء تبادل المواد.',
      addMaterials: 'إضافة المواد',
      addMaterialsDesc: 'سجل موادك الزائدة مع الصور والأوصاف والأسعار. إنه سريع وسهل!',
      sendRequests: 'إرسال الطلبات',
      sendRequestsDesc: 'تصفح المواد وأرسل طلبات إلى البائعين. تواصل مباشرة لمناقشة التفاصيل.',
      completeOrders: 'إتمام الطلبات',
      completeOrdersDesc: 'أنهِ الصفقة ورتب التسليم. بنِ علاقات أعمال مستدامة!',
      startYourJourney: 'ابدأ رحلتك',
      whatOurUsersSay: 'ماذا يقول مستخدمونا',
      usersSaySubtitle: 'اسمع من الشركات والأفراد الذين يحدثون فرقاً في الاقتصاد الدائري.',
      testimonialsNote: 'تظهر الشهادات المعتمدة هنا بعد مراجعة الإدارة. أرسل شهادتك أدناه.',
      shareYourExperience: 'شارك تجربتك',
      testimonialReviewNote: 'سيتم مراجعة شهادتك من قبل الإدارة قبل ظهورها علناً.',
      name: 'الاسم',
      roleOptional: 'الدور (اختياري)',
      rolePlaceholder: 'مشتري / صاحب مصنع / مدير...',
      testimonial: 'الشهادة',
      ratingOptional: 'التقييم (اختياري)',
      submit: 'إرسال',
      submitting: 'جارٍ الإرسال...',
      testimonialSubmitted: 'شكراً! تم إرسال شهادتك وهي في انتظار الموافقة.',
      failedToSubmit: 'فشل في إرسال الشهادة.',
      noRating: 'لا تقييم',
      clear: 'مسح',
      submitTestimonial: 'إرسال الشهادة',
      readyToMakeDifference: 'مستعد لإحداث فرق؟',
      ctaText: 'انضم إلى آلاف الشركات والأفراد الذين يقللون النفايات ويخلقون قيمة من خلال الاقتصاد الدائري.',
      createFreeAccount: 'إنشاء حساب مجاني',
      explorePlatform: 'استكشف المنصة',
      loadingProfile: 'جارٍ تحميل الملف الشخصي…',
      unableToLoadProfile: 'غير قادر على تحميل الملف الشخصي.',
      joined: 'انضم',
      // Profile form
      editProfile: 'تحرير الملف الشخصي',
      nameRequired: 'الاسم مطلوب',
      nameTooLong: 'الاسم طويل جداً',
      phoneInvalid: 'رقم الهاتف يبدو غير صحيح',
      locationTooLong: 'طويل جداً',
      bioMaxChars: 'حد أقصى 2000 حرف',
      saveProfile: 'حفظ الملف الشخصي',
      saving: 'جارٍ الحفظ...',
      profileSaved: 'تم حفظ الملف الشخصي.',
      failedToSaveProfile: 'فشل في حفظ الملف الشخصي.',
      reset: 'إعادة تعيين',
      // Password
      changePassword: 'تغيير كلمة المرور',
      currentPassword: 'كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      confirmPassword: 'تأكيد كلمة المرور',
      required: 'مطلوب',
      atLeast6Chars: 'على الأقل 6 أحرف',
      mustDiffer: 'يجب أن تختلف عن الحالية',
      passwordsDontMatch: 'كلمات المرور غير متطابقة',
      updatePassword: 'تحديث كلمة المرور',
      passwordUpdated: 'تم تحديث كلمة المرور.',
      failedToChangePassword: 'فشل في تغيير كلمة المرور.',
      showPassword: 'إظهار كلمة المرور',
      hidePassword: 'إخفاء كلمة المرور',
      // Activity
      recentActivity: 'النشاط الأخير',
      materialsListed: 'المواد المسجلة',
      requestsSent: 'الطلبات المرسلة',
      ordersCompleted: 'الطلبات المكتملة',
      accountInformation: 'معلومات الحساب',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      emailCannotBeChanged: 'لا يمكن تغيير البريد الإلكتروني بعد.',
      phone: 'الهاتف',
      phonePlaceholder: '+20 100 123 4567',
      location: 'الموقع',
      locationPlaceholder: 'المدينة، الدولة',
      bio: 'السيرة الذاتية',
      sellerBioPlaceholder: 'أخبر المشترين عن عملك، التخصصات، ومناطق التسليم.',
      buyerBioPlaceholder: 'مقدمة قصيرة عنك أو مشاريعك.',
      saveChanges: 'حفظ التغييرات',
      discard: 'تجاهل',
      // Activity labels
      myListings: 'قوائمي',
      incomingRequests: 'الطلبات الواردة',
      myRequests: 'طلباتي',
      orders: 'الطلبات',
      messages: 'الرسائل',
      rating: 'التقييم',
      // Password form
      currentPasswordRequired: 'كلمة المرور الحالية مطلوبة',
      newPasswordRequired: 'كلمة المرور الجديدة مطلوبة',
      security: 'الأمان',
      cancel: 'إلغاء',
      changePassword: 'تغيير كلمة المرور',
      keepAccountSecure: 'حافظ على أمان حسابك باستخدام كلمة مرور قوية وفريدة.',
      currentPassword: 'كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
      updatePassword: 'تحديث كلمة المرور',
      quickLinks: 'روابط سريعة',
      manageListings: 'إدارة القوائم',
      incomingRequests: 'الطلبات الواردة',
      browseMarketplace: 'تصفح السوق',
      myRequests: 'طلباتي',
      myOrders: 'طلباتي',
      adminDashboard: 'لوحة تحكم الإدارة',
      testimonialApprovals: 'موافقات الشهادات',
      approveOrRejectTestimonials: 'وافق أو ارفض الشهادات المرسلة.',
      loadingPendingTestimonials: 'جارٍ تحميل الشهادات المعلقة…',
      failedLoadTestimonials: 'فشل في تحميل موافقات الشهادات.',
      noPendingTestimonials: 'لا توجد شهادات معلقة',
      pendingTestimonialsHelp: 'يمكنك الموافقة أو الرفض عند وصول الشهادات.',
      approve: 'موافقة',
      reject: 'رفض',
      actionFailed: 'فشلت العملية. الرجاء المحاولة مرة أخرى.',
      hidePassword: 'إخفاء كلمة المرور',
      showPassword: 'إظهار كلمة المرور',
      // Game keys
      trashToss: 'رمي القمامة',
      recyclingQuiz: 'اختبار إعادة التدوير',
      recyclingQuizDescription: 'أجب على أسئلة إعادة التدوير بسرعة واكسب النقاط.',
      recyclingQuizComplete: 'اكتمل الاختبار!',
      recyclingQuizExcellent: 'ممتاز! معرفتك بإعادة التدوير قوية.',
      recyclingQuizGood: 'عمل رائع! استمر في تعلم المزيد من النصائح.',
      recyclingQuizOkay: 'بداية جيدة! الممارسة تساعدك على التحسن.',
      ecoMemory: 'الذاكرة البيئية',
      wasteSorting: 'فرز النفايات',
      carbonAdventure: 'مغامرة الكربون',
      carbonFootprintDescription: 'اختر الخيار الأكثر استدامة لكل سيناريو.',
      carbonFootprintComplete: 'اكتملت مغامرة الكربون!',
      carbonFootprintExcellent: 'رائع! كانت خياراتك البيئية ممتازة.',
      carbonFootprintGood: 'عمل رائع! لقد اتخذت خيارات مستدامة.',
      carbonFootprintOkay: 'جهد جيد! كل خيار مهم.',
      pollutionCleanup: 'تنظيف التلوث',
      pollutionCleanupHeading: '🏖️ تنظيف الشاطئ',
      pollutionCleanupDescription: 'انقر على عناصر القمامة على الشاطئ لتنظيفها قبل انتهاء الوقت.',
      beachCleanupComplete: 'اكتمل تنظيف الشاطئ!',
      pollutionCleanupSuccess: 'عمل رائع في تنظيف الشاطئ!',
      pollutionCleanupFailed: 'انتهى الوقت! حظ أفضل في المرة القادمة.',
      boost: 'تعزيز',
      trashLeft: 'القمامة المتبقية',
      clickFast: 'انقر بسرعة',
      allTrashCleaned: 'تم تنظيف كل القمامة المرئية. انتظر درجتك النهائية.',
      // Game finish messages
      gameFailed: 'اللعبة انتهت - فشلت!',
      scoreBelow100: 'درجتك أقل من 100. حاول مرة أخرى!',
      tooManyWrong: 'الكثير من الإجابات الخاطئة! اللعبة انتهت.',
      // Recycle Bin Game
      recycleBinDescription: 'حدد الحاوية الصحيحة لكل قطعة قمامة.',
      trashTossDescription: 'ألقِ عناصر القمامة في حاوية إعادة التدوير الصحيحة.',
      trashTossComplete: 'اكتمل رمي القمامة!',
      trashTossSuccess: 'لقد قمت بفرز القمامة بشكل صحيح!',
      trashTossFailed: 'انتهى الوقت أو حدثت الكثير من الأخطاء!',
      // Marketplace keys
      loadingMaterials: 'جارٍ تحميل المواد…',
      discoverSustainable: 'اكتشف المواد الزائدة المستدامة من الشركات والأفراد.',
      filtersSearch: 'التصفية والبحث',
      searchMaterials: 'البحث في المواد...',
      allCategories: 'جميع الفئات',
      allPrices: 'جميع الأسعار',
      priceLowToHigh: 'السعر: من الأقل إلى الأعلى',
      priceHighToLow: 'السعر: من الأعلى إلى الأقل',
      nameAToZ: 'الاسم: أ إلى ي',
      clearAllFilters: 'مسح جميع التصفيات',
      showingMaterials: 'يظهر',
      materials: 'مواد',
      noDescription: 'لا يوجد وصف.',
      qty: 'الكمية',
      viewDetails: 'عرض التفاصيل',
      noMaterialsFound: 'لم يتم العثور على مواد',
      tryAdjustingFilters: 'جرب تعديل تصفياتك أو استعلام البحث.',
      clearFilters: 'مسح التصفيات',
      failedLoadMarketplace: 'فشل في تحميل عناصر السوق. يرجى المحاولة مرة أخرى لاحقاً.',
      // Orders keys
      ordersDescriptionSeller: 'الطلبات التي تشمل موادك. بعد أن يدفع المشتري (تجريبي)، يمكنك وضع علامة على الطلب كمكتمل عند التنفيذ.',
      ordersDescriptionBuyer: 'ادفع باستخدام الخروج التجريبي لتأكيد الطلب، ثم يمكنك أو البائع وضع علامة على الطلب كمكتمل.',
      loadingOrders: 'جارٍ تحميل الطلبات…',
      paymentFailed: 'فشل الدفع.',
      updateFailed: 'فشل التحديث.',
      nameOnCardRequired: 'اسم على البطاقة مطلوب.',
      cardNumberRequired: 'رقم البطاقة مطلوب.',
      cardNumberInvalid: 'رقم البطاقة يبدو غير صحيح.',
      expiryRequired: 'تاريخ الانتهاء مطلوب (شهر/سنة).',
      expiryInvalid: 'استخدم شهر/سنة (مثل 08/28).',
      cardExpired: 'البطاقة منتهية الصلاحية.',
      cvvRequired: 'CVV مطلوب.',
      cvvInvalid: 'CVV يجب أن يكون 3-4 أرقام.',
      pay: 'ادفع',
      markComplete: 'وضع علامة كمكتمل',
      cancelOrder: 'إلغاء الطلب',
      status: 'الحالة',
      confirmed: 'مؤكد',
      completed: 'مكتمل',
      cancelled: 'ملغي',
      quantity: 'الكمية',
      seller: 'البائع',
      buyer: 'المشتري',
      date: 'التاريخ',
      actions: 'الإجراءات',
      noOrders: 'لا توجد طلبات بعد.',
      noOrdersMessage: 'عند شراء مواد، ستظهر طلباتك هنا.',
      // SellerIncomingRequests keys
      incomingRequests: 'الطلبات الواردة',
      respondToBuyers: 'الرد على المشترين المهتمين بقوائمك.',
      showAcceptedRejected: 'إظهار المقبول / المرفوض',
      loadingRequests: 'جارٍ تحميل الطلبات…',
      failedLoadRequests: 'فشل في تحميل الطلبات الواردة.',
      failedUpdateStatus: 'فشل في تحديث الحالة.',
      accept: 'قبول',
      reject: 'رفض',
      accepted: 'مقبول',
      rejected: 'مرفوض',
      message: 'الرسالة',
      viewListing: 'عرض القائمة',
      noRequests: 'لا توجد طلبات بعد.',
      noRequestsMessage: 'عندما يهتم المشترون بقوائمك، ستظهر الطلبات هنا.',
      // SellerListings keys
      manageListingsDesc: 'إدارة وتتبع قوائم موادك.',
      addNewListing: 'إضافة قائمة جديدة',
      title: 'العنوان',
      description: 'الوصف',
      quantity: 'الكمية',
      price: 'السعر',
      category: 'الفئة',
      selectCategory: 'اختر الفئة...',
      image: 'الصورة',
      listingAdded: 'تم إضافة القائمة بنجاح.',
      failedAddListing: 'فشل في إضافة القائمة.',
      edit: 'تحرير',
      delete: 'حذف',
      confirmDelete: 'هل أنت متأكد من حذف هذه القائمة؟',
      deleteListing: 'حذف القائمة',
      failedDelete: 'فشل في حذف القائمة.',
      noListings: 'لا توجد قوائم بعد.',
      noListingsMessage: 'أضف قائمتك الأولى لبدء بيع المواد الزائدة.',
      failedLoadListings: 'فشل في تحميل قوائمك.',
      loadingListings: 'جارٍ تحميل قوائمك...',
      listingPendingHelp: 'يتم إنشاء القوائم الجديدة كقيد الانتظار حتى موافقة المدير.',
      existingListings: 'القوائم الحالية',
      emptyListingsMessage: 'استخدم النموذج لإضافة المادة الأولى الخاصة بك.',
      howToPlay: 'كيفية اللعب',
      createNewListing: 'إنشاء قائمة جديدة',
      egSurplusCotton: 'مثل قماش قطني زائد',
      describeCondition: 'وصف الحالة، التعبئة، الملاحظات...',
      optional: 'اختياري',
      orProvideUrl: 'أو قدم URL/مسار أدناه (اختياري).',
      optionalUrl: 'اختياري (URL أو مسار)',
      // RegisterForm keys
      joinCircularEconomy: 'انضم إلى الاقتصاد الدائري—سجل أو اعثر على مواد زائدة في دقائق.',
      fillDetails: 'املأ تفاصيلك لإنشاء حساب جديد.',
      findSustainableMaterials: 'اعثر على مواد مستدامة',
      listYourSurplus: 'سجل فائضك',
      // Add more as needed
    },
  };

  const t = (key) => translations[language][key] || key;

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme, language, toggleLanguage, t }}>
      {children}
    </ThemeContext.Provider>
  );
};